version: '3'
services:
  ssmgr:
    network_mode: "host"
    env_file: 
      - "$secrets_dir/secret.env"
    image: geektr/ssmgr
    restart: always
    volumes:
      - "$service_dir/conf/ssmgr/config.js:/usr/local/share/.config/yarn/global/node_modules/shadowsocks-manager/services/config.js"
